#!/bin/bash
# Source - https://stackoverflow.com/a
# Posted by Simon Hyll, modified by community. See post 'Timeline' for change history
# Retrieved 2025-11-18, License - CC BY-SA 4.0
for f in $(git diff --name-only --cached); do
    if [[ $f == *.ipynb ]]; then
        python3 -m jupyter nbconvert --clear-output --inplace $f
        git add $f
    fi
done

if git diff --name-only --cached --exit-code
then
    echo "No changes detected after removing notebook output"
    exit 1
fi
